// Copyright 2026, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Generated from o1-labs/proof-systems tag 0.3.0 (commit a73ca6e).

fn pickles_v1_outer_linearization() -> Vec<OuterToken> {
    vec![
        OuterToken::Cell(Variable { col: Column::Index(GateType::Poseidon), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(0), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 0 }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 1 }),
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 2 }),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(1),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(1), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 0 }),
        OuterToken::Load(0),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 1 }),
        OuterToken::Load(1),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 2 }),
        OuterToken::Load(2),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(2),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(2), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 0 }),
        OuterToken::Load(0),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 1 }),
        OuterToken::Load(1),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 2 }),
        OuterToken::Load(2),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(3),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(3), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 0 }),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 1 }),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 2 }),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(4),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(4), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 0 }),
        OuterToken::Load(3),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 1 }),
        OuterToken::Load(4),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 2 }),
        OuterToken::Load(5),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(5),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(5), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 0 }),
        OuterToken::Load(3),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 1 }),
        OuterToken::Load(4),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 2 }),
        OuterToken::Load(5),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(6),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(6), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 0 }),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 1 }),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 2 }),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(7),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(7), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 0 }),
        OuterToken::Load(6),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 1 }),
        OuterToken::Load(7),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 2 }),
        OuterToken::Load(8),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(8),
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(8), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 0 }),
        OuterToken::Load(6),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 1 }),
        OuterToken::Load(7),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 2 }),
        OuterToken::Load(8),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(9),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(9), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 0 }),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 1 }),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 2 }),
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(10),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(10), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 0 }),
        OuterToken::Load(9),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 1 }),
        OuterToken::Load(10),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 2 }),
        OuterToken::Load(11),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(11),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(11), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 0 }),
        OuterToken::Load(9),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 1 }),
        OuterToken::Load(10),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 2 }),
        OuterToken::Load(11),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(12),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Coefficient(12), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 0 }),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 1 }),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 0, col: 2 }),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Pow(7),
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(13),
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Coefficient(13), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 0 }),
        OuterToken::Load(12),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 1 }),
        OuterToken::Load(13),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 1, col: 2 }),
        OuterToken::Load(14),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(14),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Coefficient(14), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 0 }),
        OuterToken::Load(12),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 1 }),
        OuterToken::Load(13),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Mds { row: 2, col: 2 }),
        OuterToken::Load(14),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Index(GateType::VarBaseMul), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(1),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(2),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(3),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Load(17),
        OuterToken::Mul,
        OuterToken::Load(16),
        OuterToken::Load(16),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(15),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(4),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Load(16),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(17),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(5),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(6),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(7),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Load(20),
        OuterToken::Mul,
        OuterToken::Load(19),
        OuterToken::Load(19),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(18),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(8),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Load(19),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(20),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(9),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(10),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(11),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Load(23),
        OuterToken::Mul,
        OuterToken::Load(22),
        OuterToken::Load(22),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(21),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(12),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Load(22),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(23),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(13),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(14),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(15),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Load(26),
        OuterToken::Mul,
        OuterToken::Load(25),
        OuterToken::Load(25),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(24),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(16),
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Load(25),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(26),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(17),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(18),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Next }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(19),
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Next }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Load(29),
        OuterToken::Mul,
        OuterToken::Load(28),
        OuterToken::Load(28),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(27),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(20),
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Load(28),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Load(29),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Index(GateType::CompleteAdd), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(1),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Load(30),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(2),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Sub,
        OuterToken::Load(31),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Load(30),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(3),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(4),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(5),
        OuterToken::Load(32),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(6),
        OuterToken::Load(32),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Index(GateType::EndoMul), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(1),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(2),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(3),
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(4),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::EndoCoefficient),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(5),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Sub,
        OuterToken::Load(33),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(35),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(6),
        OuterToken::Load(36),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Load(35),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Load(34),
        OuterToken::Load(33),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(7),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::EndoCoefficient),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x1, 0x0, 0x0, 0x0]))),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(8),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Sub,
        OuterToken::Load(37),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Store,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Next }),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(39),
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(9),
        OuterToken::Load(40),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Load(39),
        OuterToken::Dup,
        OuterToken::Mul,
        OuterToken::Load(38),
        OuterToken::Load(37),
        OuterToken::Sub,
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Next }),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(10),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(14), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Next }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Index(GateType::EndoMulScalar), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(1),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xd96cf90b00000001, 0x60c232feaddc3849, 0x5555555555555555, 0x1555555555555555]))),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xc62375907ffffffe, 0x11234c7e04ca546e, 0x0, 0x2000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xecb67c8580000002, 0xb061197f56ee1c24, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaa]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Store,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(2),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(41),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(42),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(43),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(44),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(45),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(46),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(47),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Dup,
        OuterToken::Add,
        OuterToken::Load(48),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x3, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Sub,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(3),
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(6), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(4),
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(7), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(5),
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(8), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(6),
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(9), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(7),
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(10), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(8),
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(11), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(9),
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(12), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(10),
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0xb, 0x0, 0x0, 0x0]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Constant(ConstantTerm::Literal(outer_field([0x8c46eb20fffffffb, 0x224698fc0994a8dd, 0x0, 0x4000000000000000]))),
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Witness(13), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Index(GateType::Generic), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Coefficient(0), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Coefficient(1), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Coefficient(2), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(2), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Coefficient(3), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(0), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(1), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Coefficient(4), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Challenge(BerkeleyChallengeTerm::Alpha),
        OuterToken::Pow(1),
        OuterToken::Cell(Variable { col: Column::Coefficient(5), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Coefficient(6), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Coefficient(7), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(5), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Coefficient(8), row: CurrOrNext::Curr }),
        OuterToken::Cell(Variable { col: Column::Witness(3), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Cell(Variable { col: Column::Witness(4), row: CurrOrNext::Curr }),
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Cell(Variable { col: Column::Coefficient(9), row: CurrOrNext::Curr }),
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Add,
        OuterToken::Mul,
        OuterToken::Add,
    ]
}
