// Copyright 2026, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Frozen PicklesV1 linearization constant.
//!
//! The Pickles statement is part of the proof protocol. It must use the
//! constraint expression shipped by the Pickles-era proof system, rather than
//! whichever expression is generated by the Kimchi crate used to verify the
//! outer proof. `legacy_tokens.rs` is generated from proof-systems tag 0.3.0.

use alloc::vec::Vec;

use ark_ff::{BigInt, Field, One, PrimeField, Zero};
use ark_poly::Radix2EvaluationDomain as D;
use kimchi::proof::{PointEvaluations, ProofEvaluations};
use mina_curves::pasta::{Fp, Pallas};
use mina_poseidon::pasta::fp_kimchi;
use poly_commitment::ipa::endos;

use crate::{format::FeatureFlags, prepared::PreparedError};

#[derive(Clone, Copy)]
enum LegacyToken {
    Literal([u64; 4]),
    Challenge(LegacyChallenge),
    Cell(LegacyColumn, bool),
    Endo,
    Mds(usize, usize),
    Vanishes,
    Lagrange(bool, i32),
    Pow(u64),
    Add,
    Mul,
    Sub,
    Double,
    Square,
    If(LegacyFeature, usize, usize),
}

#[derive(Clone, Copy)]
enum LegacyChallenge {
    Alpha,
    Beta,
    Gamma,
    JointCombiner,
}

#[allow(dead_code)]
#[derive(Clone, Copy)]
enum LegacyColumn {
    Witness(usize),
    Z,
    LookupSorted(usize),
    LookupAggreg,
    LookupTable,
    LookupKindIndex(LegacyLookupPattern),
    LookupRuntimeSelector,
    LookupRuntimeTable,
    Index(LegacyGate),
    Coefficient(usize),
    Permutation(usize),
}

#[derive(Clone, Copy)]
enum LegacyGate {
    Generic,
    Poseidon,
    CompleteAdd,
    VarBaseMul,
    EndoMul,
    EndoMulScalar,
    RangeCheck0,
    RangeCheck1,
    ForeignFieldAdd,
    ForeignFieldMul,
    Xor16,
    Rot64,
}

#[derive(Clone, Copy)]
enum LegacyLookupPattern {
    Xor,
    Lookup,
    RangeCheck,
    ForeignFieldMul,
}

#[derive(Clone, Copy)]
enum LegacyFeature {
    RangeCheck0,
    RangeCheck1,
    ForeignFieldAdd,
    ForeignFieldMul,
    Xor,
    Rot,
    LookupTables,
    RuntimeLookupTables,
    LookupPattern(LegacyLookupPattern),
    TableWidth(isize),
    LookupsPerRow(isize),
}

include!("legacy_tokens.rs");

pub(super) struct Context<'a> {
    pub evals: &'a ProofEvaluations<PointEvaluations<Fp>>,
    pub domain: D<Fp>,
    pub zeta: Fp,
    pub alpha: Fp,
    pub beta: Fp,
    pub gamma: Fp,
    pub joint_combiner: Option<Fp>,
    pub feature_flags: FeatureFlags,
    pub zk_rows: u64,
}

pub(super) fn constant_term(context: &Context<'_>) -> Result<Fp, PreparedError> {
    evaluate(PICKLES_V1_CONSTANT_TOKENS, context)
}

fn evaluate(tokens: &[LegacyToken], context: &Context<'_>) -> Result<Fp, PreparedError> {
    let mut stack = Vec::new();
    let mut cursor = 0;
    while cursor < tokens.len() {
        match tokens[cursor] {
            LegacyToken::Literal(limbs) => {
                stack.push(Fp::from_bigint(BigInt::new(limbs)).ok_or(PreparedError::Evaluation)?)
            }
            LegacyToken::Challenge(challenge) => stack.push(match challenge {
                LegacyChallenge::Alpha => context.alpha,
                LegacyChallenge::Beta => context.beta,
                LegacyChallenge::Gamma => context.gamma,
                LegacyChallenge::JointCombiner => {
                    context.joint_combiner.ok_or(PreparedError::Evaluation)?
                }
            }),
            LegacyToken::Cell(column, next) => stack.push(evaluate_cell(column, next, context)),
            LegacyToken::Endo => stack.push(endos::<Pallas>().0),
            LegacyToken::Mds(row, column) => {
                stack.push(fp_kimchi::static_params().mds[row][column]);
            }
            LegacyToken::Vanishes => stack.push(if context.joint_combiner.is_none() {
                Fp::one()
            } else {
                let omega_minus_four = context
                    .domain
                    .group_gen
                    .pow([context.domain.size - context.zk_rows - 1]);
                let omega_minus_one = context
                    .domain
                    .group_gen
                    .inverse()
                    .ok_or(PreparedError::Evaluation)?;
                let omega_minus_two = omega_minus_one.square();
                let omega_minus_three = omega_minus_two * omega_minus_one;
                (context.zeta - omega_minus_one)
                    * (context.zeta - omega_minus_two)
                    * (context.zeta - omega_minus_three)
                    * (context.zeta - omega_minus_four)
            }),
            LegacyToken::Lagrange(zk_rows, offset) => {
                let exponent = if zk_rows {
                    i64::from(offset) - context.zk_rows as i64
                } else {
                    i64::from(offset)
                }
                .rem_euclid(context.domain.size as i64) as u64;
                let root = context.domain.group_gen.pow([exponent]);
                stack.push(
                    (context.zeta.pow([context.domain.size]) - Fp::one())
                        * (context.zeta - root)
                            .inverse()
                            .ok_or(PreparedError::Evaluation)?,
                );
            }
            LegacyToken::Pow(power) => {
                let value = stack.pop().ok_or(PreparedError::Evaluation)?;
                stack.push(value.pow([power]));
            }
            LegacyToken::Add => binary(&mut stack, |left, right| left + right)?,
            LegacyToken::Mul => binary(&mut stack, |left, right| left * right)?,
            LegacyToken::Sub => binary(&mut stack, |left, right| left - right)?,
            LegacyToken::Double => {
                let value = stack.pop().ok_or(PreparedError::Evaluation)?;
                stack.push(value + value);
            }
            LegacyToken::Square => {
                let value = stack.pop().ok_or(PreparedError::Evaluation)?;
                stack.push(value.square());
            }
            LegacyToken::If(feature, enabled_len, disabled_len) => {
                let branches = &tokens[cursor + 1..cursor + 1 + enabled_len + disabled_len];
                let chosen = if feature_enabled(feature, context) {
                    &branches[..enabled_len]
                } else {
                    &branches[enabled_len..]
                };
                stack.push(evaluate(chosen, context)?);
                cursor += enabled_len + disabled_len;
            }
        }
        cursor += 1;
    }
    if stack.len() != 1 {
        return Err(PreparedError::Evaluation);
    }
    stack.pop().ok_or(PreparedError::Evaluation)
}

fn binary(stack: &mut Vec<Fp>, operation: impl FnOnce(Fp, Fp) -> Fp) -> Result<(), PreparedError> {
    let right = stack.pop().ok_or(PreparedError::Evaluation)?;
    let left = stack.pop().ok_or(PreparedError::Evaluation)?;
    stack.push(operation(left, right));
    Ok(())
}

fn evaluate_cell(column: LegacyColumn, next: bool, context: &Context<'_>) -> Fp {
    let evals = context.evals;
    let value = match column {
        LegacyColumn::Witness(index) => Some(evals.w[index]),
        LegacyColumn::Z => Some(evals.z),
        LegacyColumn::LookupSorted(index) => evals.lookup_sorted[index],
        LegacyColumn::LookupAggreg => evals.lookup_aggregation,
        LegacyColumn::LookupTable => evals.lookup_table,
        LegacyColumn::LookupRuntimeSelector => evals.runtime_lookup_table_selector,
        LegacyColumn::LookupRuntimeTable => evals.runtime_lookup_table,
        LegacyColumn::Coefficient(index) => Some(evals.coefficients[index]),
        LegacyColumn::Permutation(index) => Some(evals.s[index]),
        LegacyColumn::LookupKindIndex(pattern) => match pattern {
            LegacyLookupPattern::Xor => evals.xor_lookup_selector,
            LegacyLookupPattern::Lookup => evals.lookup_gate_lookup_selector,
            LegacyLookupPattern::RangeCheck => evals.range_check_lookup_selector,
            LegacyLookupPattern::ForeignFieldMul => evals.foreign_field_mul_lookup_selector,
        },
        LegacyColumn::Index(gate) => match gate {
            LegacyGate::Generic => Some(evals.generic_selector),
            LegacyGate::Poseidon => Some(evals.poseidon_selector),
            LegacyGate::CompleteAdd => Some(evals.complete_add_selector),
            LegacyGate::VarBaseMul => Some(evals.mul_selector),
            LegacyGate::EndoMul => Some(evals.emul_selector),
            LegacyGate::EndoMulScalar => Some(evals.endomul_scalar_selector),
            LegacyGate::RangeCheck0 => evals.range_check0_selector,
            LegacyGate::RangeCheck1 => evals.range_check1_selector,
            LegacyGate::ForeignFieldAdd => evals.foreign_field_add_selector,
            LegacyGate::ForeignFieldMul => evals.foreign_field_mul_selector,
            LegacyGate::Xor16 => evals.xor_selector,
            LegacyGate::Rot64 => evals.rot_selector,
        },
    };
    value.map_or_else(Fp::zero, |evaluation| {
        if next {
            evaluation.zeta_omega
        } else {
            evaluation.zeta
        }
    })
}

fn feature_enabled(feature: LegacyFeature, context: &Context<'_>) -> bool {
    // Pickles uses no feature environment when there is no joint combiner.
    if context.joint_combiner.is_none() {
        return false;
    }
    let flags = context.feature_flags;
    let range_check_lookup = flags.range_check0 || flags.range_check1 || flags.rot;
    let lookups_per_row_4 = flags.xor || range_check_lookup || flags.foreign_field_mul;
    let lookups_per_row_3 = lookups_per_row_4 || flags.lookup;
    let table_width_3 = flags.xor;
    let table_width_at_least_2 = table_width_3 || flags.lookup;
    let table_width_at_least_1 =
        table_width_at_least_2 || range_check_lookup || flags.foreign_field_mul;
    match feature {
        LegacyFeature::RangeCheck0 => flags.range_check0,
        LegacyFeature::RangeCheck1 => flags.range_check1,
        LegacyFeature::ForeignFieldAdd => flags.foreign_field_add,
        LegacyFeature::ForeignFieldMul => flags.foreign_field_mul,
        LegacyFeature::Xor => flags.xor,
        LegacyFeature::Rot => flags.rot,
        LegacyFeature::LookupTables => lookups_per_row_3,
        LegacyFeature::RuntimeLookupTables => flags.runtime_tables,
        LegacyFeature::LookupPattern(LegacyLookupPattern::Lookup) => flags.lookup,
        LegacyFeature::LookupPattern(LegacyLookupPattern::Xor) => flags.xor,
        LegacyFeature::LookupPattern(LegacyLookupPattern::RangeCheck) => range_check_lookup,
        LegacyFeature::LookupPattern(LegacyLookupPattern::ForeignFieldMul) => {
            flags.foreign_field_mul
        }
        LegacyFeature::TableWidth(width) => match width {
            3 => table_width_3,
            2 => table_width_at_least_2,
            width if width <= 1 => table_width_at_least_1,
            _ => false,
        },
        LegacyFeature::LookupsPerRow(width) => match width {
            4 => lookups_per_row_4,
            width if width <= 3 => lookups_per_row_3,
            _ => false,
        },
    }
}
